name: Alpha Realease

on:
  pull_request:
    branches: [ master ]

jobs:
  unitTest:
    name: Lint and unit test

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Decode Firebase google-services.json
        env:
          FIREBASE_CONFIG: ${{ secrets.FIREBASE_CONFIG }}
        run: echo $FIREBASE_CONFIG > app/google-services.json

      - name: Decode Playstore key
        env:
          PLAY_KEY: ${{ secrets.PLAY_KEY }}
        run: echo $PLAY_KEY > app/keys/play-key.json

      - name: Run ktlint
        run: ./gradlew ktlint

      - name: Run Android lint
        run: ./gradlew lintDebug

      - name: Run unit tests
        run: ./gradlew testDebugUnitTest
      
      
  release:
    name: Upload Alpha Release
    needs: [unitTest]
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Upload Release
        run: bash ./gradlew publishReleaseBundle
