name: workflow

on:
  push:
    branches:
      - master
      - develop

jobs:
  testing:
    name: Lint and unit test

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Decode Firebase google-services.json
        env:
          FIREBASE_CONFIG: ${{ secrets.FIREBASE_CONFIG }}
        run: echo $FIREBASE_CONFIG > app/google-services.json

      - name: Decode Playstore key
        env:
          PLAY_KEY: ${{ secrets.PLAY_KEY }}
        run: echo $PLAY_KEY > app/play-key.json

      - name: Decode Release keystore base64
        env:
          RELEASE_KEYSTORE: ${{ secrets.RELEASE_KEYSTORE }}
        run: echo $RELEASE_KEYSTORE > app/Christ_key.asc
      - name: Decode Release keystore file
        env:
          PASSPHRASE: ${{ secrets.KEY_PASSPHRASE }}
        run: gpg -d --passphrase $PASSPHRASE --batch app/Christ_key.asc > app/Christ_key

      - name: Decode Keystore properties file
        env:
          KEY_PROPERTIES: ${{ secrets.KEY_STORE_PROPERTIES }}
        run: echo $KEY_PROPERTIES > app/keystore.properties

      - name: Run ktlint
        run: ./gradlew ktlint

      - name: Run Android lint
        run: ./gradlew lintDebug

      - name: Run unit tests
        run: ./gradlew testDebugUnitTest
